#!/usr/bin/env bash 

set -e -x

for index in {1..4}
do {
  mkdir -p "./freebsd-pg-${index}"
  pushd "./freebsd-pg-${index}"

  # pastebin.com/raw/n66vwpDm
  cat > Vagrantfile <<-VAGRANTFILE
	mac = \`printf '00602F%02X%02X%02X' $[RANDOM%256] $[RANDOM%256] $[RANDOM%256]\`

	Vagrant.configure("2") do |config|
    config.vm.guest = :freebsd
    config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true
    config.vm.box = "freebsd/FreeBSD-11.0-CURRENT"
    config.vm.base_mac = "#{mac}" # "080027D14C66"
    config.ssh.shell = "sh"
		config.vm.network "private_network", ip: "10.11.11.1${index}"

    config.vm.provision :shell, :path => "./scripts/provision-centos7"

    config.vm.provider :virtualbox do |v|
        v.name = "freebsd-pg-${index}"
        v.customize ["modifyvm", :id, "--memory", "1024"]
        v.customize ["modifyvm", :id, "--cpus", "1"]
        v.customize ["modifyvm", :id, "--hwvirtex", "on"]
        v.customize ["modifyvm", :id, "--audio", "none"]
        v.customize ["modifyvm", :id, "--nictype1", "virtio"]
        v.customize ["modifyvm", :id, "--nictype2", "virtio"]
    end

    config.vm.provider :vmware_fusion do |v|
      v.name = "freebsd-pg-${index}"
      v.vmx["memsize"] = "1024"
      v.vmx["numvcpus"] = "1"
    end
  end
VAGRANTFILE
  vagrant up
  popd
  }&
done

wait

exit $?
