#!/usr/bin/env bash 

set -e -x

for index in {1..3}
do {
  mkdir -p "./centos7-pg-${index}"
  pushd "./centos7-pg-${index}"

  # pastebin.com/raw/n66vwpDm
  cat > Vagrantfile <<-VAGRANTFILE
	mac = \`printf '00602F%02X%02X%02X' $[RANDOM%256] $[RANDOM%256] $[RANDOM%256]\`

	Vagrant.configure("2") do |config|
    config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true
    config.vm.box = "geerlingguy/centos7"
    config.vm.base_mac = "#{mac}" # "080027D14C66"
    config.ssh.shell = "bash"
		config.vm.network "private_network", ip: "10.11.11.7${index}"

    config.vm.provision :shell, inline: "echo '10.11.11.7${index}' > /tmp/ip"
    config.vm.provision "file", source: "../scripts/bootstrap-projects", destination: "/tmp/bootstrap-projects"
    config.vm.provision :shell, :path => "../scripts/provision-centos7"

    config.vm.provider :virtualbox do |v|
        v.name = "centos7-pg-${index}"
        v.customize ["modifyvm", :id, "--memory", "1024"]
        v.customize ["modifyvm", :id, "--cpus", "1"]
        v.customize ["modifyvm", :id, "--hwvirtex", "on"]
        v.customize ["modifyvm", :id, "--audio", "none"]
        v.customize ["modifyvm", :id, "--nictype1", "virtio"]
        v.customize ["modifyvm", :id, "--nictype2", "virtio"]
    end

    config.vm.provider :vmware_fusion do |v|
      v.name = "centos7-pg-${index}"
      v.vmx["memsize"] = "1024"
      v.vmx["numvcpus"] = "1"
    end
  end
VAGRANTFILE
  vagrant up
  popd
  }&
done

wait

exit $?
