#!/usr/bin/env bash

export PATH="${PATH}:/usr/local/go/bin:${HOME}/go/bin"
export GOPATH="${HOME}/go"

mkdir -p "${GOPATH}"/{src,bin,pkg}

go install github.com/mitchellh/gox

for project in consul vault
do go get github.com/hashicorp/${project}
done

pushd ~/go/src/github.com/hashicorp/consul
make dev build
popd

pushd ~/go/src/github.com/hashicorp/vault
make dev build
popd

[[ -s "${HOME}/consul/key" ]] ||
  "${GOPATH}/bin/consul" keygen > "${HOME}/consul/key"

mkdir -p ~/bin ~/consul/conf.d

masterToken="MasterTokenGoesHereWeeeee"

cat > ~/consul/config.json <<EOF 
{
    "acl_datacenter": "lab1",
    "acl_default_policy": "deny",
    "acl_master_token": "${masterToken}",
    "addresses": {
        "dns": "0.0.0.0",
        "http": "unix:///tmp/.consul.http.sock",
        "https": "0.0.0.0",
        "rpc": "unix:///tmp/.consul.rpc.sock"
    },
    "bootstrap_expect": 3,
    "datacenter": "lab1",
    "data_dir": "${HOME}/consul/data",
    "disable_remote_exec": true,
    "dns_config": {
        "allow_stale": true,
        "max_stale": "10080m",
        "node_ttl": "60s",
        "service_ttl": {
            "*": "5s",
            "stable-service": "86400s"
        }
    },
    "encrypt": "$(cat "${HOME}/consul/key")",
    "log_level": "debug",
    "ports": {
        "https": -1
    },
    "server": true,
    "unix_sockets": {
        "mode": "0700"
    }
}
EOF

cat > ~/bin/run-consul <<EOF 
#!/bin/bash

set -e
exec 2>&1
exec /usr/bin/env -i "${GOPATH}/bin/consul" agent \
    -config-file=~/consul/config.json \
    -config-dir=~/consul/conf.d/
EOF

chmod 0755 ~/bin/run-consul

if ! grep -q GOROOT ~/.bash_profile
then
  cat >> ~/.bash_profile <<-EOF
export PATH="\${PATH}:/usr/local/go/bin:\${HOME}/go/bin"
export GOPATH="\${HOME}/go"

export CONSUL_RPC_ADDR=/tmp/.consul.rpc.sock
export CONSUL_HTTP_ADDR=/tmp/.consul.http.sock
EOF
fi

~/bin/run-consul

